version: 2

sources:
  - name: paytunes_data
    description: All mongo data goes here
    tables:
      - name: bid_floor_video
        description: >
          One record per order. Includes cancelled and deleted orders.
      - name: bid_floor_ctv
        description: >
          One record per order. Includes cancelled and deleted orders.
      - name: bid_floor_display
        description: >
          One record per order. Includes cancelled and deleted orders.
      - name: bid_floor_audio
        description: >
          One record per order. Includes cancelled and deleted orders.
        # columns:
        #   - name: id
        #     description: Primary key of the orders table
        #     tests:
        #       - unique
        #       - not_null
        #   - name: status
        #     description: Note that the status can change over time
